# Name of your dbt project
name: 'dbt_jet_case_study'
version: '0.0.1'
config-version: 2

profile: 'dbt_jet_case_study'
model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  jet_case_study:
    materialized: view
    staging:
      materialized: view
    marts:
      materialized: table

