name: 'dbt_xkcd'
version: '1.0.0'

profile: 'duckdb_profile'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:    
  - "target"
  - "dbt_packages"

models:
  dbt_xkcd:
    staging:
      +materialized: table

