version: 2

models:
  - name: stg_comic
    columns:
      - name: comic_id
        tests:
          - unique
          - not_null
        
      - name: safe_title
        tests:
          - not_null  
      
      - name: release_year
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1900
              inclusive: true

      - name: release_month
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

      - name: release_day
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 31